version: "2"

run:
  timeout: 10m
  tests: false
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
  settings:
    govet:
      disable-all: true
      enable:
        - fieldalignment

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
