package grammargen

import (
	"strings"
	"testing"
)

const generatedFixture = `// Code generated by tsgo-generate; DO NOT EDIT.
package fixture

import (
	core "github.com/dcosson/treesitter-go/internal/core"
	language "github.com/dcosson/treesitter-go/language"
)

func languageFixture() *language.Language {
	return &language.Language{
		Version:                14,
	}
}
`

func TestRewriteGenerated(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name              string
		correctABIVersion bool
		wantVersion       string
	}{
		{name: "public facade", wantVersion: "Version:                14,"},
		{name: "C# ABI metadata", correctABIVersion: true, wantVersion: "Version:                15,"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			rewritten, err := rewriteGenerated([]byte(generatedFixture), test.correctABIVersion)
			if err != nil {
				t.Fatalf("rewriteGenerated() error = %v", err)
			}
			text := string(rewritten)
			for _, forbidden := range []string{
				"treesitter-go/internal/core",
				"treesitter-go/language",
				"language.Language",
			} {
				if strings.Contains(text, forbidden) {
					t.Errorf("rewriteGenerated() retained %q", forbidden)
				}
			}
			for _, required := range []string{
				`core "github.com/dcosson/treesitter-go"`,
				"*core.Language",
				"&core.Language",
				test.wantVersion,
			} {
				if !strings.Contains(text, required) {
					t.Errorf("rewriteGenerated() omitted %q", required)
				}
			}
		})
	}
}

func TestRewriteGeneratedRejectsDrift(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		source string
		abi    bool
		want   string
	}{
		{
			name:   "core import missing",
			source: strings.Replace(generatedFixture, string(internalCoreImport), string(publicCoreImport), 1),
			want:   "exactly one internal core import",
		},
		{
			name:   "language import missing",
			source: strings.Replace(generatedFixture, string(languageImport), "", 1),
			want:   "exactly one internal language import",
		},
		{
			name:   "language type missing",
			source: strings.ReplaceAll(generatedFixture, "language.Language", "core.Language"),
			want:   "does not reference language.Language",
		},
		{
			name:   "ABI metadata missing",
			source: strings.Replace(generatedFixture, string(legacyABIVersion), "Version: 14,", 1),
			abi:    true,
			want:   "exactly one ABI 14 metadata field",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			_, err := rewriteGenerated([]byte(test.source), test.abi)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("rewriteGenerated() error = %v, want containing %q", err, test.want)
			}
		})
	}
}

func TestRemoveLineContainingPreservesFinalLine(t *testing.T) {
	t.Parallel()

	got := removeLineContaining([]byte("keep\nremove marker\nlast"), []byte("marker"))
	if string(got) != "keep\nlast" {
		t.Fatalf("removeLineContaining() = %q, want %q", got, "keep\\nlast")
	}
}
