//go:build ignore

// Command split rewrites tsgo-generate's single enormous Swift lexer into
// small helpers. The state machine and all lexer actions remain unchanged;
// only dispatch between generated state cases moves across function calls.
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"strconv"
	"strings"
)

const lexerStatesPerHelper = 64

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: go run split.go INPUT_GO OUTPUT_GO")
		os.Exit(2)
	}
	inputPath, outputPath := os.Args[1], os.Args[2]
	source, err := os.ReadFile(inputPath)
	if err != nil {
		fatalf("read generated source: %v", err)
	}

	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, inputPath, source, parser.SkipObjectResolution)
	if err != nil {
		fatalf("parse generated source: %v", err)
	}
	declarationIndex, lexer := findLexer(file)
	if lexer == nil {
		fatalf("generated tsLex function not found")
	}
	stateCases, err := lexerStateCases(lexer)
	if err != nil {
		fatalf("inspect generated tsLex: %v", err)
	}
	helpers := (len(stateCases) + lexerStatesPerHelper - 1) / lexerStatesPerHelper
	dispatcher, err := parseFunction(dispatcherSource(helpers))
	if err != nil {
		fatalf("build lexer dispatcher: %v", err)
	}

	replacements := make([]ast.Decl, 0, helpers+1)
	replacements = append(replacements, dispatcher)
	for helperIndex := range helpers {
		start := helperIndex * lexerStatesPerHelper
		end := min(start+lexerStatesPerHelper, len(stateCases))
		for _, stateCase := range stateCases[start:end] {
			if err := rewriteReturns(stateCase); err != nil {
				fatalf("rewrite helper %d: %v", helperIndex, err)
			}
		}
		helper, err := parseFunction(helperSource(helperIndex))
		if err != nil {
			fatalf("build lexer helper %d: %v", helperIndex, err)
		}
		switchStatement, err := functionSwitch(helper)
		if err != nil {
			fatalf("inspect lexer helper %d: %v", helperIndex, err)
		}
		switchStatement.Body.List = make([]ast.Stmt, 0, end-start+1)
		for _, stateCase := range stateCases[start:end] {
			switchStatement.Body.List = append(switchStatement.Body.List, stateCase)
		}
		switchStatement.Body.List = append(switchStatement.Body.List, dispatchCase())
		replacements = append(replacements, helper)
	}

	declarations := make([]ast.Decl, 0, len(file.Decls)+helpers)
	declarations = append(declarations, file.Decls[:declarationIndex]...)
	declarations = append(declarations, replacements...)
	declarations = append(declarations, file.Decls[declarationIndex+1:]...)
	file.Decls = declarations
	clearTokenPositions(reflect.ValueOf(file))

	output, err := os.Create(outputPath)
	if err != nil {
		fatalf("create split output: %v", err)
	}
	if _, err := output.WriteString("// Code generated by tsgo-generate; DO NOT EDIT.\n\n"); err != nil {
		_ = output.Close()
		fatalf("write generated header: %v", err)
	}
	if err := format.Node(output, token.NewFileSet(), file); err != nil {
		_ = output.Close()
		fatalf("format split output: %v", err)
	}
	if err := output.Close(); err != nil {
		fatalf("close split output: %v", err)
	}
}

func findLexer(file *ast.File) (int, *ast.FuncDecl) {
	for index, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if ok && function.Name.Name == "tsLex" {
			return index, function
		}
	}
	return -1, nil
}

func lexerStateCases(function *ast.FuncDecl) ([]*ast.CaseClause, error) {
	switchStatement, err := functionSwitch(function)
	if err != nil {
		return nil, err
	}
	stateCases := make([]*ast.CaseClause, 0, len(switchStatement.Body.List)-1)
	for _, statement := range switchStatement.Body.List {
		stateCase, ok := statement.(*ast.CaseClause)
		if !ok {
			return nil, fmt.Errorf("switch contains %T", statement)
		}
		if len(stateCase.List) == 0 {
			continue
		}
		if len(stateCase.List) != 1 {
			return nil, fmt.Errorf("state case has %d expressions", len(stateCase.List))
		}
		literal, ok := stateCase.List[0].(*ast.BasicLit)
		if !ok || literal.Kind != token.INT {
			return nil, fmt.Errorf("state expression is %T", stateCase.List[0])
		}
		state, err := strconv.Atoi(literal.Value)
		if err != nil {
			return nil, fmt.Errorf("state %q: %w", literal.Value, err)
		}
		if state != len(stateCases) {
			return nil, fmt.Errorf("state %d follows %d", state, len(stateCases)-1)
		}
		stateCases = append(stateCases, stateCase)
	}
	if len(stateCases) == 0 {
		return nil, fmt.Errorf("no lexer states")
	}
	return stateCases, nil
}

func functionSwitch(function *ast.FuncDecl) (*ast.SwitchStmt, error) {
	if function.Body == nil || len(function.Body.List) == 0 {
		return nil, fmt.Errorf("function has no body")
	}
	forStatement, ok := function.Body.List[len(function.Body.List)-1].(*ast.ForStmt)
	if !ok || forStatement.Body == nil || len(forStatement.Body.List) != 1 {
		return nil, fmt.Errorf("last statement is not the generated lexer loop")
	}
	switchStatement, ok := forStatement.Body.List[0].(*ast.SwitchStmt)
	if !ok || switchStatement.Body == nil {
		return nil, fmt.Errorf("lexer loop does not contain a switch")
	}
	return switchStatement, nil
}

func rewriteReturns(stateCase *ast.CaseClause) error {
	var rewriteError error
	ast.Inspect(stateCase, func(node ast.Node) bool {
		if rewriteError != nil {
			return false
		}
		returnStatement, ok := node.(*ast.ReturnStmt)
		if !ok {
			return true
		}
		if len(returnStatement.Results) != 1 {
			rewriteError = fmt.Errorf("return has %d results", len(returnStatement.Results))
			return false
		}
		returned := returnStatement.Results[0]
		switch value := returned.(type) {
		case *ast.Ident:
			if value.Name != "result" && value.Name != "false" {
				rewriteError = fmt.Errorf("unexpected return identifier %q", value.Name)
				return false
			}
		default:
			rewriteError = fmt.Errorf("unexpected return expression %T", returned)
			return false
		}
		returnStatement.Results = []ast.Expr{
			ast.NewIdent("state"),
			returned,
			ast.NewIdent("true"),
		}
		return true
	})
	return rewriteError
}

func dispatcherSource(helperCount int) string {
	var source strings.Builder
	source.WriteString("package generated\n\n")
	source.WriteString("func tsLex(lexer *lex.Lexer, state core.StateID) bool {\n")
	source.WriteString("\tresult := false\n\tfor {\n\t\tvar done bool\n")
	fmt.Fprintf(&source, "\t\tswitch int(state) / %d {\n", lexerStatesPerHelper)
	for helperIndex := range helperCount {
		fmt.Fprintf(
			&source,
			"\t\tcase %d:\n\t\t\tstate, result, done = tsLexStates%d(lexer, state, result)\n",
			helperIndex,
			helperIndex,
		)
	}
	source.WriteString("\t\tdefault:\n\t\t\treturn false\n\t\t}\n")
	source.WriteString("\t\tif done {\n\t\t\treturn result\n\t\t}\n\t}\n}\n")
	return source.String()
}

func helperSource(index int) string {
	return fmt.Sprintf(`package generated

func tsLexStates%d(
	lexer *lex.Lexer,
	state core.StateID,
	result bool,
) (core.StateID, bool, bool) {
	lookahead := lexer.Lookahead
	eof := lexer.EOF()
	_ = eof
	for {
		switch state {
		default:
			return state, result, false
		}
	}
}
`, index)
}

func parseFunction(source string) (*ast.FuncDecl, error) {
	parsed, err := parser.ParseFile(
		token.NewFileSet(),
		"generated.go",
		source,
		parser.SkipObjectResolution,
	)
	if err != nil {
		return nil, err
	}
	if len(parsed.Decls) != 1 {
		return nil, fmt.Errorf("snippet has %d declarations", len(parsed.Decls))
	}
	function, ok := parsed.Decls[0].(*ast.FuncDecl)
	if !ok {
		return nil, fmt.Errorf("snippet declaration is %T", parsed.Decls[0])
	}
	return function, nil
}

var tokenPositionType = reflect.TypeOf(token.Pos(0))

func clearTokenPositions(value reflect.Value) {
	if !value.IsValid() {
		return
	}
	if value.Type() == tokenPositionType {
		if value.CanSet() {
			value.SetInt(0)
		}
		return
	}
	switch value.Kind() {
	case reflect.Interface, reflect.Pointer:
		if !value.IsNil() {
			clearTokenPositions(value.Elem())
		}
	case reflect.Slice:
		for index := range value.Len() {
			clearTokenPositions(value.Index(index))
		}
	case reflect.Struct:
		for index := range value.NumField() {
			clearTokenPositions(value.Field(index))
		}
	}
}

func dispatchCase() *ast.CaseClause {
	return &ast.CaseClause{
		Body: []ast.Stmt{
			&ast.ReturnStmt{Results: []ast.Expr{
				ast.NewIdent("state"),
				ast.NewIdent("result"),
				ast.NewIdent("false"),
			}},
		},
	}
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", arguments...)
	os.Exit(1)
}
